name: Lint and Format

on: [pull_request]

jobs:
  wpiformat:
    name: "buildifier"
    runs-on: ubuntu-latest
    steps:
      - uses: bazelbuild/setup-bazelisk@v1
      - uses: actions/checkout@v2
      - name: Run buildifier
        run: buildifier --lint=fix -r .
      - name: Check Output
        run: git --no-pager diff --exit-code HEAD